//! Backend-neutral license exchange traits.

use std::future::Future;
use std::pin::Pin;

use base64::Engine as _;

use crate::{ContentKey, Error, KeyId, KeySet};

/// A boxed asynchronous operation used by object-safe DRM traits.
pub type BoxFuture<'a, T> = Pin<Box<dyn Future<Output = T> + Send + 'a>>;

/// The kind of media content named in a license request.
#[non_exhaustive]
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum ContentType {
    /// Video content.
    Video,
    /// Audio content.
    Audio,
}

/// Inputs required to acquire keys for one protection-system initialization.
///
/// This type deliberately does not implement `Debug` because it owns PSSH and
/// playback-token material.
pub struct DrmRequest {
    /// Configured Crunchyroll license endpoint.
    pub endpoint: String,
    /// Modern content identifier.
    pub content_id: String,
    /// Playback session token.
    pub playback_token: String,
    /// Media kind associated with the protected track.
    pub content_type: ContentType,
    /// Binary PSSH box or protection-system payload.
    pub pssh: Vec<u8>,
}

/// An outbound license request generated by a DRM provider.
///
/// This type deliberately does not implement `Debug` or serialization traits.
pub struct LicenseRequest {
    /// Configured license endpoint.
    pub endpoint: String,
    /// Modern content identifier for `x-cr-content-id`.
    pub content_id: String,
    /// Playback token for `x-cr-video-token`.
    pub playback_token: String,
    /// Whether the challenge belongs to video or audio.
    pub content_type: ContentType,
    /// Binary or XML license challenge.
    pub challenge: Vec<u8>,
}

/// Raw license bytes returned by a transport.
///
/// This type deliberately does not implement `Debug` or serialization traits.
pub struct LicenseResponse(Vec<u8>);

impl LicenseResponse {
    /// Wrap a binary license response.
    #[must_use]
    pub fn binary(bytes: Vec<u8>) -> Self {
        Self(bytes)
    }

    /// Decode a binary response or a JSON object containing a base64 license.
    ///
    /// Accepted JSON field names are `license`, `data`, and `payload`.
    ///
    /// # Errors
    ///
    /// Returns [`Error::License`] for malformed JSON or base64 data.
    pub fn from_http(content_type: Option<&str>, body: Vec<u8>) -> Result<Self, Error> {
        if !content_type.is_some_and(|value| value.to_ascii_lowercase().contains("json")) {
            return Ok(Self::binary(body));
        }
        let value: serde_json::Value = serde_json::from_slice(&body).map_err(|_| Error::License)?;
        let encoded = ["license", "data", "payload"]
            .iter()
            .find_map(|field| value.get(field).and_then(serde_json::Value::as_str))
            .ok_or(Error::License)?;
        let bytes = base64::engine::general_purpose::STANDARD
            .decode(encoded)
            .map_err(|_| Error::License)?;
        Ok(Self(bytes))
    }

    /// Borrow the raw response for backend-specific license parsing.
    #[must_use]
    pub fn as_bytes(&self) -> &[u8] {
        &self.0
    }
}

/// Application-provided transport for DRM license challenges.
pub trait LicenseTransport: Send + Sync {
    /// Send one license request and return its response body.
    fn send<'a>(&'a self, request: LicenseRequest)
    -> BoxFuture<'a, Result<LicenseResponse, Error>>;
}

/// A DRM backend that turns PSSH and a license response into content keys.
pub trait DrmProvider: Send + Sync {
    /// Generate a challenge, exchange it through `transport`, and parse keys.
    fn acquire_keys<'a>(
        &'a self,
        request: DrmRequest,
        transport: &'a dyn LicenseTransport,
    ) -> BoxFuture<'a, Result<KeySet, Error>>;
}

/// Acquire and match keys for independently licensed tracks.
///
/// Results preserve request order. Each returned key is checked against that
/// track's declared default KID before the next license is requested.
///
/// # Errors
///
/// Returns the first provider, transport, or missing-key error.
pub fn acquire_track_keys<'a>(
    provider: &'a dyn DrmProvider,
    transport: &'a dyn LicenseTransport,
    tracks: Vec<(KeyId, DrmRequest)>,
) -> BoxFuture<'a, Result<Vec<ContentKey>, Error>> {
    Box::pin(async move {
        let mut matched = Vec::with_capacity(tracks.len());
        for (kid, request) in tracks {
            let keys = provider.acquire_keys(request, transport).await?;
            matched.push(keys.require(kid)?.clone());
        }
        Ok(matched)
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    struct EchoTransport;

    impl LicenseTransport for EchoTransport {
        fn send<'a>(
            &'a self,
            request: LicenseRequest,
        ) -> BoxFuture<'a, Result<LicenseResponse, Error>> {
            Box::pin(async move { Ok(LicenseResponse::binary(request.challenge)) })
        }
    }

    struct FixtureProvider;

    impl DrmProvider for FixtureProvider {
        fn acquire_keys<'a>(
            &'a self,
            request: DrmRequest,
            transport: &'a dyn LicenseTransport,
        ) -> BoxFuture<'a, Result<KeySet, Error>> {
            Box::pin(async move {
                let response = transport
                    .send(LicenseRequest {
                        endpoint: request.endpoint,
                        content_id: request.content_id,
                        playback_token: request.playback_token,
                        content_type: request.content_type,
                        challenge: request.pssh,
                    })
                    .await?;
                let marker = *response.as_bytes().first().ok_or(Error::License)?;
                let mut keys = KeySet::new();
                keys.insert(
                    KeyId::new([marker; 16]),
                    ContentKey::try_from_slice(&[marker.wrapping_add(1); 16])?,
                );
                Ok(keys)
            })
        }
    }

    #[test]
    fn unwraps_json_license_response() {
        let response = LicenseResponse::from_http(
            Some("application/json; charset=utf-8"),
            br#"{"license":"AQIDBA=="}"#.to_vec(),
        )
        .unwrap();
        assert_eq!(response.as_bytes(), &[1, 2, 3, 4]);
    }

    #[test]
    fn preserves_binary_license_response() {
        let response =
            LicenseResponse::from_http(Some("application/octet-stream"), vec![0, 255, 17]).unwrap();
        assert_eq!(response.as_bytes(), &[0, 255, 17]);
    }

    #[tokio::test]
    async fn independently_licenses_audio_and_video() {
        let request = |marker, content_type| DrmRequest {
            endpoint: "https://license.invalid".to_string(),
            content_id: "content".to_string(),
            playback_token: format!("token-{marker}"),
            content_type,
            pssh: vec![marker],
        };
        let keys = acquire_track_keys(
            &FixtureProvider,
            &EchoTransport,
            vec![
                (KeyId::new([3; 16]), request(3, ContentType::Video)),
                (KeyId::new([7; 16]), request(7, ContentType::Audio)),
            ],
        )
        .await
        .unwrap();

        assert_eq!(keys[0].expose(), &[4; 16]);
        assert_eq!(keys[1].expose(), &[8; 16]);
    }
}
